### ISSUE TITLE
Duplicate columns user data

### ISSUE THREAD

**Issue by kpatel427** [vnsny-bia/VisitContactTrace#9]
The application fails to throw an error and notify user if user has a duplicate ‘required’ column with same name (app crashed when I had two columns with name ‘patient_id’).

**Comment by rushabh31** [comment]
This issue has been resolved. It now raises an error for duplicated columns. Please find screenshot below for reference.

![image](https://user-images.githubusercontent.com/50964981/84508581-7e276300-ac90-11ea-98ef-79e89eafba0d.png)
